name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - prod
      - 'feature/**'
      - 'bugfix/**'
      - 'chore/**'
      - 'hotfix/**'
    tags: [ "v*" ]

  pull_request:
    branches:
      - main
      - dev
      - prod

jobs:
  unit-tests:
    name: Unit Tests (PHP 8.4)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none
          extensions: mbstring, xml, simplexml

      - name: Validate composer.json
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Composer Security Audit
        run: composer audit

      - name: Run PHPUnit
        run: vendor/bin/phpunit tests/ --colors=never